name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # se ejecuta cada d√≠a a medianoche
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update stats
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api?username=diegoalvarezf&show_icons=true&include_all_commits=true&count_private=true&theme=dracula&locale=en&hide_border=false&token=${{ secrets.GH_TOKEN }}"
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update GitHub stats"
          git push
